logging:
  config: classpath:logback-spring.xml
server:
  port: 8082
spring:
  application:
    name: rpc-server

rpc:
  server:
    zk:
      #根节点
      root: /rpc
      #Zookeeper服务地址
      addr: 43.138.86.137:2181
      #链接超时时间
      timeout: 1000
  #Rpc通信端口->Netty端口
  network:
    port: 28889