server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: rpc-client

rpc:
  client:
    zk:
      root: /rpc
      addr: 43.138.86.137:2181
      switch: true
      timeout: 10000
    api:
      package: org.example.api
  cluster:
    strategy: random